### PR TITLE
AIP-6392: Add in automated git tagging

### PR DESCRIPTION
**Pull request by alexlatchford**
See it working [here](https://gitlab.zgtools.net/analytics/artificial-intelligence/ai-platform/aip-workflow/zillow-metaflow/-/jobs/13671347)

### CODE REVIEW

**Comment by cloudw** [comment]
I think I like the idea of auto tagging, but I have two concerns for these OSS github repo mirrored in gitlab. @alexlatchford 
- The same customized version format should be used for tagging, to distinguish from OSS version tags. So tag `${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_IID}+${METAFLOW_VERSION}` following the same schema here https://github.com/zillow/metaflow/blob/ba1d03ac02681744d6df247af14161fa2822baee/metaflow/plugins/kfp/tests/.gitlab-ci.yml#L37-L51. Alternatively tag with something like `zg-${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_IID}` is also fine.
- Tags are not synced automatically from gitlab to github. I think in short term a manual git tag push is fine. Mostly I'm composing release log from git tags, which has been a manual process.

**Comment by alexlatchford** [comment]
> * The same customized version format should be used for tagging, to distinguish from OSS version tags. So tag `${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_IID}+${METAFLOW_VERSION}` following the same schema here https://github.com/zillow/metaflow/blob/ba1d03ac02681744d6df247af14161fa2822baee/metaflow/plugins/kfp/tests/.gitlab-ci.yml#L37-L51
>   . Alternatively tag with something like `zg-${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_IID}` is also fine.

Yeah good call, let me make amendments here and in `zillow/pipelines` too to make sure the tags align with the versioning we use. Thanks for calling this out!

> * Tags are not synced automatically from gitlab to github. I think in short term a manual git tag push is fine. Mostly I'm composing release log from git tags, which has been a manual process.

Yeah I don't really know how best to handle this to be honest and think manual is likely the best short-term option, maybe if we want to utilize Github Actions to do the auto-tagging in the near future that might work better assuming tags are synced? 

I've also started to think about how to extend this paradigm to include some auto-release notes functionality. In short the crux of the idea is to:

1. For every new tag use the [Create Release](https://docs.gitlab.com/ee/api/releases/#create-a-release) API to create a release, the description would with a link to the commit or PR that produced that tag. This would work for every `vX.Y.Z` release, basically all patches.
2. For every `vX` and `vX.Y` tag, which we currently force push for every patch release on the first release we'd do the same as above. But for every subsequent one we'd use the "Update Release" API and basically append a line to the existing release notes.

It doesn't quite solve the problem of manually generated release notes which are nicely summarized for human consumption, but having an ordered list of all the PR titles with links back I think would be a good start. Thoughts?

**Comment by cloudw** [comment]
> let me make amendments here and in zillow/pipelines too to make sure the tags align with the versioning we use. Thanks for calling this out!
> ... Yeah I don't really know how best to handle this to be honest and think manual is likely the best short-term option, maybe if we want to utilize Github Actions to do the auto-tagging in the near future that might work better assuming tags are synced?

Maybe we just write a similar version of auto git tag scripts with github action? This github action can then be shared across OSS project that zillow forked.

> It doesn't quite solve the problem of manually generated release notes which are nicely summarized for human consumption, but having an ordered list of all the PR titles with links back I think would be a good start. Thoughts?

I have been using github to automatically generate release notes: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes I then do minor editing on top, but if all MR titles are well written not much editing is needed. `What's changed` session of this release https://github.com/zillow/metaflow/releases/tag/zg-1.2 is entirely auto-generated 

One release note per minor version feels reasonable to me. So maybe a semi-manual process with automated change log is fine - as developer is already manually incrementing minor version.

**Comment by alexlatchford** [comment]
Closing this as taking Yun's suggestion to do this via Github Actions, will reopen another PR

**Pull request closed without merging**
