### PR TITLE
Add back unit test coverage

### PR DESCRIPTION
**Pull request by cloudw**

### CODE REVIEW

**Comment by talebzeghmi** [comment]
This seems fine for now.  But we'd like to know why did Metaflow origin remove coverage and how do they now get coverage?  This question is more important as we move to Argo which will not have this same code coverage approach.

**Review by talebzeghmi — APPROVED** [review]

**Comment by cloudw** [comment]
> This seems fine for now. But we'd like to know why did Metaflow origin remove coverage and how do they now get coverage? This question is more important as we move to Argo which will not have this same code coverage approach.

Outerbounds do not rely on test coverage to gauge their releases. They do have unit test but they also have code that can't be tested in unit tests. They mainly do canary testing.

**Comment by talebzeghmi** [comment]
>Outerbounds do not rely on test coverage to gauge their releases. They do have unit test but they also have code that can't be tested in unit tests. They mainly do canary testing.
We need this for customer Flow code coverage rather than Metaflow coverage.

**Comment by cloudw** [comment]
> > Outerbounds do not rely on test coverage to gauge their releases. They do have unit test but they also have code that can't be tested in unit tests. They mainly do canary testing.

> We need this for customer Flow code coverage rather than Metaflow coverage.

Agreed. That's why Outerbounds removes `coverage` while we keep it.

**Pull request merged**
