### PR TITLE
AIP-7796 Embed zillow-kfp compiler into WFSDK

### PR DESCRIPTION
**Pull request by talebzeghmi**
* This PR embeds the KFP client to compile Flows into Argo Workflows.
* 16 transitive dependency removals!!

The following are the first-level transitive dependencies we were able to remove and simplify from zillow-kfp https://github.com/zillow/pipelines/blob/6e2d7b24e3cbeb97cd1329733635151da3115c34/sdk/python/setup.py#L25-L59

```bash
❯ doit poetry add "zillow-metaflow@2.0.2417.dev2417+2.5.4"

Writing lock file

Package operations: 0 installs, 2 updates, 16 removals

  • Removing cloudpickle (2.2.1)
  • Removing google-api-core (2.10.2)
  • Removing google-api-python-client (1.12.11)
  • Removing google-auth-httplib2 (0.1.0)
  • Removing google-cloud-core (2.3.2)
  • Removing google-cloud-storage (1.44.0)
  • Removing google-crc32c (1.5.0)
  • Removing google-resumable-media (2.4.1)
  • Removing httplib2 (0.21.0)
  • Removing pydantic (1.10.6)
  • Removing pyparsing (3.0.9)
  • Removing strip-hints (0.1.10)
  • Removing tabulate (0.9.0)
  • Removing typer (0.7.0)
  • Removing wheel (0.40.0)
  • Removing zillow-kfp (1.0.81+1.8.10)
  • Updating pyyaml (5.4.1 -> 6.0.1)
  • Updating zillow-metaflow (2.0.2416.dev2416+2.5.4 -> 2.0.2417.dev2417+2.5.4)
```

```diff
31,33d27
<         "click>=7.1.2,<9",
<         "cloudpickle>=2.0.0,<3",
<         'dataclasses;python_version<"3.7"',
37,39c31
<         "google-api-python-client>=1.7.8,<2",
<         "google-auth>=1.6.1,<2",
<         "google-cloud-storage>=1.20.0,<2",
---
>         "googleapis-common-protos>=1.6.0,<2",
45,46c37
<         "pydantic>=1.8.2,<2",
<         "PyYAML>=5.3,<6",
---
>         "pyyaml>=6.0.1,<7",
48,51d38
<         "strip-hints>=0.1.8,<1",
<         "tabulate>=0.8.6,<1",
<         "typer>=0.3.2,<1.0",
<         'typing-extensions>=3.7.4,<4;python_version<"3.9"',
```

### CODE REVIEW

**Comment by alexlatchford** [comment]
Generally looks good, is this working because the existing `aip` plugin imports from `kfp`? Or is it not actually hooked up yet and requires some more PRs to actually utilize that code and potentially in the future slim it down to just what we're actively using?

**Comment by talebzeghmi** [comment]
> Generally looks good, is this working because the existing aip plugin imports from kfp? Or is it not actually hooked up yet and requires some more PRs to actually utilize that code and potentially in the future slim it down to just what we're actively using?

it's done and works because `kfp` is installed as a top level `py_modules` on `pip install`!
see related PR https://gitlab.zgtools.net/analytics/artificial-intelligence/ai-platform/aip-infrastructure/dockerfiles/aip-py/-/merge_requests/186#6a5ddfa118ee33f1381cfd1f4ff5751ac4f1b81f

**Comment by alexlatchford** [comment]
> it's done and works because `kfp` is installed as a top level `py_modules` on `pip install`! see related PR https://gitlab.zgtools.net/analytics/artificial-intelligence/ai-platform/aip-infrastructure/dockerfiles/aip-py/-/merge_requests/186#6a5ddfa118ee33f1381cfd1f4ff5751ac4f1b81f

Oh I think I get it, sorry your link confused me 😅 I think you maybe meant to sent [this line](https://github.com/zillow/metaflow/blob/tz/AIP-7796-embed-kfp/setup.py#L16). I see `kfp` in the `py_modules` in `setup.py` for `zillow-metaflow` and therefore when the `aip` plugin does `import kfp` it'll immediately go to this local reference which is super nice!

Firstly, this is a great leap forward, thanks for making this change but I wonder if we can think about next steps here:
1. Can we slim down the `kfp` module as is to just the bits we need?
2. Can we replace `kfp` compiler with the native Metaflow Argo Workflows one?

I do think as well having a discussion about what it'd take (likely via an RFC) to move `zillow-metaflow` to be a Metaflow plugin instead of a fork too. Unclear to me if that's a fully supported pattern in Metaflow but I'm guessing we're starting to fall seriously behind the Metaflow `main` branch in terms of versioning now?

**Review by alexlatchford — APPROVED** [review]

**Comment by talebzeghmi** [comment]
@alexlatchford , thank you! 
> Can we slim down the kfp module as is to just the bits we need?

we could... but takes extra work with little benefit for now, because copying the whole `kfp` module is one operation, otherwise must edit `__init__.py` and maybe other kfp top level files (ex: _auth.py, etc)

* Created this task and onto my backlog to ensure I do this soon: [AIP-7832](https://zillowgroup.atlassian.net/browse/AIP-7832) RFC on WFSDK kfp->argo next steps

**Pull request merged**
