### PR TITLE
AIP-6788 Optional PVC volume_type

### PR DESCRIPTION
**Pull request by talebzeghmi**

### CODE REVIEW

**Review by alexlatchford — APPROVED** [review]
Looks good, I do wonder about whether we want to make a syntax that would cope with passing through any parameter for the PVC Spec ([link](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#persistentvolumeclaimspec-v1-core)) but I guess I'll leave that to you as the SDK interface owner. This change definitely couples us more to PVC (and K8s) and makes `@resources` less agnostic but how to handle these platform-specific configurable attributes seems tricky :/

**Comment by alexlatchford** [comment]
Also any chance of extending the `@resources` tests to include an assertion on this?

**Comment by aaron-arellano** [comment]
Are we going to update documentation or add a comment somewhere explaining what a `storage class` is and why it is needed here? Might also be helpful to add in the concern from Devex. Would be worth adding cause for me to understand I have to reference the Devex thread and also look up storage class kubernetes [documentation](https://kubernetes.io/docs/concepts/storage/storage-classes/).

**Comment by cloudw** [comment]
+1 for @aaron-arellano 's request to add reference, so that we know why this feature is needed retrospectively.

**Comment by cloudw** [comment]
Shall we default storage class to EBS for volumes, instead of creating a new field here? 

The request was "DevEx is requesting we expose the storage_class_name for PVCs", should it be exposed as a label on the pod, instead of as a filed on SDK user side?

**Comment by talebzeghmi** [comment]
@aaron-arellano I added comments and link to the AIP-6788 bug in the code
@alexlatchford I updated the resourcs_flow.py test to use the new volume_type.  It is not easy to determine the PVC type attached (without using the k8s client), however the test itself would fail if the volume_type cannot be attached, so no need to assert.
@aaron-arellano regarding our Sphynx documentation: as per the [thread](https://zillowgroup.slack.com/archives/C017WHU8551/p1667231564281969), we'll evaluate how this works with ZNN, then determine whether to update the default storage class for all, and whether to expose the `volume_type` to our customers (we can keep it hidden).

thank you!

**Review by cloudw — APPROVED** [review]

**Pull request merged**
