### PR TITLE
Raising unimplemented error for unsupported decorators.

### PR DESCRIPTION
**Pull request by cloudw**

### CODE REVIEW

**Comment by alexlatchford** [comment]
Do we have a way to write tests for this?

**Comment by talebzeghmi** [comment]
> Do we have a way to write tests for this?

It could be a new pytest file in https://github.com/zillow/metaflow/tree/feature/kfp/metaflow/plugins/kfp/tests

**Comment by cloudw** [comment]
An "expected failed" test feature that we currently do not have is required. I can add it but expect a bit more time to be taken.

**Comment by cloudw** [comment]
The R test failure relies on pulling some commit from netflix master branch: https://github.com/zillow/metaflow/pull/62

**Comment by cloudw** [comment]
Look good to me. I think we don't need any unit test since these unimplemented errors are manually tested right?

Merge pending on approvals.

**Comment by cloudw** [comment]
> Do we have a way to write tests for this?

Maybe we can make sure all decorator that we claim supported have tests.

**Comment by talebzeghmi** [comment]
> Look good to me. I think we don't need any unit test since these unimplemented errors are manually tested right?
Yes, it's manually tested for a quick friendly error.  The flow would anyhow fail even if this check has a bug, but with an unfriendly error.  So I too don't think a unit test is necessary.

**Comment by talebzeghmi** [comment]
> Maybe we can make sure all decorator that we claim supported have tests - not necessary in this PR. We can create ticket for adding a complete test suit.

The decorators already have unit tests, for example `@timeout` https://github.com/zillow/metaflow/blob/a721c60b181f9c2704ac901d9dac65da04167286/test/core/tests/timeout_decorator.py#L10-L10

**Review by talebzeghmi — APPROVED** [review]

**Pull request merged**
