### PR TITLE
Adding Gitlab CI - build and publish only

### PR DESCRIPTION
**Pull request by cloudw**
Context: 
We build and test this package using zg gitlab mirror to allow integration testing on zg infra.

Changes: 
- Add .gitlab-ci.yml for building and publishing zillow-metaflow.

Future TODOs:
- Add testing scripts - pending on zillow plug-in testing strategy and a test folder path

### CODE REVIEW

**Comment by alexlatchford** [comment]
Hmm, I see this is going into a new `zillow/argo` branch. Do we know roughly what we think we need to fork from the open source at this stage or is merely exploratory?

**Comment by cloudw** [comment]
> Hmm, I see this is going into a new `zillow/argo` branch. Do we know roughly what we think we need to fork from the open source at this stage or is merely exploratory?

I'd say it's still exploratory, and more discussion will be needed. For now I just want to make sure a build happens and can be used for testing, potentially allowing Chris to test his flow triggering code on some example projects.

Me and @talebzeghmi were thinking that two things can help reducing the amount of work for merging from netflix/metaflow and contributing back.
- Write new features on master branch and create PRs to both `netflix/metaflow/master` and `zillow/metaflow/zillow/argo`. This avoids dumping zg commits specific into `netflix/metaflow/master`.
- Make ZG specialization a plug-in (more thinking and planning needed) so that less merge conflicts happens when pulling in upstream changes.

I don't think these two bullet points completely solves the issue since feature changes require slightly more work, thus open to other solution as well.

**Comment by alexlatchford** [comment]
> Me and @talebzeghmi were thinking that two things can help reducing the amount of work for merging from netflix/metaflow and contributing back.

Yeah I think this is the crux of it, I understand this will improve the development flow but I guess my question is what developments do we think we need to support that Vanilla Metaflow doesn't? Do we have that gap analysis? Sounds like flow triggering flow is one but wondering what others we have planned. 

I guess I'm trying to understand how we don't end up with a large amount of forked code again and whether we're thinking of adopting a slightly different model this time around to at least try to contribute back substantial amounts of code upstream or whether we think that's too tough to achieve.

**Comment by cloudw** [comment]
> Yeah I think this is the crux of it, I understand this will improve the development flow but I guess my question is what developments do we think we need to support that Vanilla Metaflow doesn't? Do we have that gap analysis? Sounds like flow triggering flow is one but wondering what others we have planned.
> 
> I guess I'm trying to understand how we don't end up with a large amount of forked code again and whether we're thinking of adopting a slightly different model this time around to at least try to contribute back substantial amounts of code upstream or whether we think that's too tough to achieve.

We have a rough list of features to verify against Vanilla Metaflow in this [google doc](https://docs.google.com/document/d/1hEQJ-Dbsoe4ZG8Qg-zGPZnF60cWueztMWopNlIRfMjY/edit#heading=h.dmxqfaf3xd8h), and I do believe that many can be contributed back. My hesitation for contributing any part of KFP plug-in back was that the plugin was built specifically to ZG's use case and is hard to hand back piece by piece if KFP plug-in wasn't entirely accepted, but it's no longer the case for argo plug-in. Some specializations like zodiac team & service tag will stay in zillow's branch.

Here is a PR for allowing a hello world from ZG clusters: https://github.com/zillow/metaflow/pull/180/files

**Comment by talebzeghmi** [comment]
> Some specializations like zodiac team & service tag will stay in zillow's branch.

Ideally this will be in the ZG specialization plug-in.  
But true, we will need a `zillow/metaflow/zillow/argo` feature branch for Argo features/bug fixes that `netflix/metaflow/master` doesn't accept at the speed necessary for our customers.

An added complication is that every Argo feature/bug fix needs two PRs:
1. A PR against `netflix/metaflow/master` 
2. A PR against `zillow/metaflow/zillow/argo`

I'll restart the Metaflow/Zillow syncs to discuss this once we begin design/development.

**Pull request closed without merging**
